// <auto-generated />
using System;
using DanielLooptEnBeleeftApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DanielLooptEnBeleeftApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317142522_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DanielLooptEnBeleeftApi.Domain.Entities.RaceReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ReportText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RunningRaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RunningRaceId")
                        .IsUnique();

                    b.ToTable("RaceReports");
                });

            modelBuilder.Entity("DanielLooptEnBeleeftApi.Domain.Entities.RunningRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeCategoryPlace")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<int>("DistanceUnit")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("FinishTime")
                        .HasColumnType("time");

                    b.Property<string>("LinkToRaceReport")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LinkToRaceResult")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LinkToRaceWebsite")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("NumberParticipantsAgeCategory")
                        .HasColumnType("int");

                    b.Property<int?>("NumberParticipantsOverall")
                        .HasColumnType("int");

                    b.Property<int?>("OverallPlace")
                        .HasColumnType("int");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RacePlace")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan?>("RaceStartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("RunningRaces");
                });

            modelBuilder.Entity("DanielLooptEnBeleeftApi.Domain.Entities.RaceReport", b =>
                {
                    b.HasOne("DanielLooptEnBeleeftApi.Domain.Entities.RunningRace", "RunningRace")
                        .WithOne("RaceReport")
                        .HasForeignKey("DanielLooptEnBeleeftApi.Domain.Entities.RaceReport", "RunningRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RunningRace");
                });

            modelBuilder.Entity("DanielLooptEnBeleeftApi.Domain.Entities.RunningRace", b =>
                {
                    b.Navigation("RaceReport");
                });
#pragma warning restore 612, 618
        }
    }
}
